# Generated by Django 3.1 on 2020-09-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='claimer',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hint',
            name='discord_id',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hint',
            name='response',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hint',
            name='status',
            field=models.CharField(choices=[('NR', 'No response'), ('ANS', 'Answered'), ('REF', 'Refunded'), ('OBS', 'Obsolete')], default='NR', max_length=3),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='body_template',
            field=models.CharField(blank=True, help_text='File name of a Django template (including .html) under\n        puzzle_bodies and solution_bodies containing the puzzle and\n        solution content, respectively. Defaults to slug + ".html" if not\n        specified.', max_length=500),
        ),
    ]
