# Generated by Django 3.1 on 2020-09-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0002_auto_20200921_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='metas',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='order',
            field=models.IntegerField(default=0, help_text='Used to tiebreak order of puzzle presentation of puzzles with the same threshold', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='reward',
            field=models.IntegerField(default=0, help_text='Amount of points solving this puzzle earns', verbose_name='Reward'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='round',
            field=models.IntegerField(default=0, help_text='Which round this puzzle is in; 0-indexed', verbose_name='Round'),
        ),
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(choices=[('MS', 'Middle School'), ('HS', 'High School'), ('OP', 'Open')], default='OP', help_text='Categorization of teams based on e.g. year/age range, for separate leaderboards', max_length=2),
            preserve_default=False,
        ),
    ]
