# Generated by Django 3.2.15 on 2022-09-03 22:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0003_auto_20210801_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answersubmission',
            options={'verbose_name': 'answer submission', 'verbose_name_plural': 'answer submissions'},
        ),
        migrations.AlterModelOptions(
            name='erratum',
            options={'verbose_name': 'erratum', 'verbose_name_plural': 'errata'},
        ),
        migrations.AlterModelOptions(
            name='extraguessgrant',
            options={'verbose_name': 'extra guess grant', 'verbose_name_plural': 'extra guess grants'},
        ),
        migrations.AlterModelOptions(
            name='hint',
            options={'verbose_name': 'hint', 'verbose_name_plural': 'hints'},
        ),
        migrations.AlterModelOptions(
            name='puzzle',
            options={'verbose_name': 'puzzle', 'verbose_name_plural': 'puzzles'},
        ),
        migrations.AlterModelOptions(
            name='puzzlemessage',
            options={'verbose_name': 'puzzle message', 'verbose_name_plural': 'puzzle messages'},
        ),
        migrations.AlterModelOptions(
            name='puzzleunlock',
            options={'verbose_name': 'puzzle unlock', 'verbose_name_plural': 'puzzle unlocks'},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'verbose_name': 'round', 'verbose_name_plural': 'rounds'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'survey', 'verbose_name_plural': 'surveys'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'team', 'verbose_name_plural': 'teams'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'team member', 'verbose_name_plural': 'team members'},
        ),
        migrations.AlterField(
            model_name='answersubmission',
            name='is_correct',
            field=models.BooleanField(verbose_name='Is correct'),
        ),
        migrations.AlterField(
            model_name='answersubmission',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzle', verbose_name='puzzle'),
        ),
        migrations.AlterField(
            model_name='answersubmission',
            name='submitted_answer',
            field=models.CharField(max_length=255, verbose_name='Submitted answer'),
        ),
        migrations.AlterField(
            model_name='answersubmission',
            name='submitted_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Submitted datetime'),
        ),
        migrations.AlterField(
            model_name='answersubmission',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.team', verbose_name='team'),
        ),
        migrations.AlterField(
            model_name='answersubmission',
            name='used_free_answer',
            field=models.BooleanField(verbose_name='Used free answer'),
        ),
        migrations.AlterField(
            model_name='erratum',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='erratum',
            name='puzzle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzle', verbose_name='puzzle'),
        ),
        migrations.AlterField(
            model_name='erratum',
            name='puzzle_text',
            field=models.TextField(blank=True, help_text='\n        Text to show on the puzzle page. If blank, it will not appear there. HTML is ok.\n    ', verbose_name='Puzzle text'),
        ),
        migrations.AlterField(
            model_name='erratum',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='erratum',
            name='updates_text',
            field=models.TextField(blank=True, help_text='\n        Text to show on the Updates (errata) page. If blank, it will not appear there.\n        Use $PUZZLE to refer to the puzzle. HTML is ok.\n    ', verbose_name='Updates text'),
        ),
        migrations.AlterField(
            model_name='extraguessgrant',
            name='extra_guesses',
            field=models.IntegerField(verbose_name='Extra guesses'),
        ),
        migrations.AlterField(
            model_name='extraguessgrant',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzle', verbose_name='puzzle'),
        ),
        migrations.AlterField(
            model_name='extraguessgrant',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.team', verbose_name='team'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='answered_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Answered datetime'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='claimed_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Claimed datetime'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='claimer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Claimer'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='discord_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Discord id'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='hint_question',
            field=models.TextField(verbose_name='Hint question'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='is_followup',
            field=models.BooleanField(default=False, verbose_name='Is followup'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='notify_emails',
            field=models.CharField(default='none', max_length=255, verbose_name='Notify emails'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzle', verbose_name='puzzle'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='response',
            field=models.TextField(blank=True, verbose_name='Response'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='status',
            field=models.CharField(choices=[('NR', 'No response'), ('ANS', 'Answered'), ('REF', 'Refunded'), ('OBS', 'Obsolete')], default='NR', max_length=3, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='submitted_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Submitted datetime'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.team', verbose_name='team'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='answer',
            field=models.CharField(help_text='Answer (fine if unnormalized)', max_length=255, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='body_template',
            field=models.CharField(blank=True, help_text='File name of a Django template (including .html) under\n        puzzle_bodies and solution_bodies containing the puzzle and\n        solution content, respectively. Defaults to slug + ".html" if not\n        specified.', max_length=255, verbose_name='Body template'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='emoji',
            field=models.CharField(default=':question:', help_text='Emoji to use in Discord integrations involving this puzzle', max_length=32, verbose_name='Emoji'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='is_meta',
            field=models.BooleanField(default=False, verbose_name='Is meta'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.round', verbose_name='round'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='slug',
            field=models.SlugField(help_text='Slug used in URLs to identify this puzzle (must be unique)', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='unlock_global',
            field=models.IntegerField(default=-1, help_text='If nonnegative, puzzle unlocks after N main round solves in any round.', verbose_name='Unlock global'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='unlock_hours',
            field=models.IntegerField(default=-1, help_text='If nonnegative, puzzle unlocks N hours after the hunt starts.', verbose_name='Unlock hours'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='unlock_local',
            field=models.IntegerField(default=-1, help_text='If nonnegative, puzzle unlocks after N main round solves in this round.', verbose_name='Unlock local'),
        ),
        migrations.AlterField(
            model_name='puzzlemessage',
            name='guess',
            field=models.CharField(max_length=255, verbose_name='Guess'),
        ),
        migrations.AlterField(
            model_name='puzzlemessage',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzle', verbose_name='puzzle'),
        ),
        migrations.AlterField(
            model_name='puzzlemessage',
            name='response',
            field=models.TextField(verbose_name='Response'),
        ),
        migrations.AlterField(
            model_name='puzzleunlock',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzle', verbose_name='puzzle'),
        ),
        migrations.AlterField(
            model_name='puzzleunlock',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.team', verbose_name='team'),
        ),
        migrations.AlterField(
            model_name='puzzleunlock',
            name='unlock_datetime',
            field=models.DateTimeField(verbose_name='Unlock datetime'),
        ),
        migrations.AlterField(
            model_name='puzzleunlock',
            name='view_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='View datetime'),
        ),
        migrations.AlterField(
            model_name='round',
            name='meta',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_meta': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='puzzles.puzzle', verbose_name='meta'),
        ),
        migrations.AlterField(
            model_name='round',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='round',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='round',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzle', verbose_name='puzzle'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.team', verbose_name='team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='If a team is hidden, it will not be visible to the public', verbose_name='Is hidden'),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_prerelease_testsolver',
            field=models.BooleanField(default=False, help_text='Whether this team is a prerelease testsolver. If true, the\n        team will have access to puzzles before the hunt starts', verbose_name='Is prerelease testsolver'),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_solve_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last solve time'),
        ),
        migrations.AlterField(
            model_name='team',
            name='start_offset',
            field=models.DurationField(default=datetime.timedelta, help_text='How much earlier this team should start, for early-testing\n        teams; be careful with this!', verbose_name='Start offset'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(help_text='Public team name for scoreboards and communications', max_length=255, unique=True, verbose_name='Team name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='total_free_answers_awarded',
            field=models.IntegerField(default=0, help_text='Number of additional free answers to award the team (on\n        top of the default amount per day)', verbose_name='Total free answers awarded'),
        ),
        migrations.AlterField(
            model_name='team',
            name='total_hints_awarded',
            field=models.IntegerField(default=0, help_text='Number of additional hints to award the team (on top of\n        the default amount per day)', verbose_name='Total hints awarded'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.team', verbose_name='team'),
        ),
    ]
