# Generated by Django 3.2.15 on 2022-09-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0004_auto_20220903_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='submitted_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Submitted datetime'),
        ),
        migrations.AddField(
            model_name='team',
            name='allow_time_unlocks',
            field=models.BooleanField(default=True, help_text='Whether this team receives time-unlocked puzzles. Note that\n        if disabled, they may be able to access more puzzles by logging out', verbose_name='Allow time unlocks'),
        ),
        migrations.AlterField(
            model_name='erratum',
            name='puzzle_text',
            field=models.TextField(blank=True, help_text='\n        Text to show on the puzzle page. If blank, it will not appear there.\n        The text will be prefixed with "On (date)," when displayed, so you\n        should capitalize it the way it would appear mid-sentence. HTML is ok.\n    ', verbose_name='Puzzle text'),
        ),
        migrations.AlterField(
            model_name='erratum',
            name='updates_text',
            field=models.TextField(blank=True, help_text='\n        Text to show on the Updates (errata) page. If blank, it will not appear there.\n        Use $PUZZLE to refer to the puzzle. The text will be prefixed with "On\n        (date)," when displayed, so you should capitalize it the way it would\n        appear mid-sentence. HTML is ok.\n    ', verbose_name='Updates text'),
        ),
        migrations.AlterUniqueTogether(
            name='survey',
            unique_together=set(),
        ),
    ]
